"""add message

Revision ID: 10821bbc6b7d
Revises: 21be14a1e621
Create Date: 2024-02-10 19:39:21.245502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10821bbc6b7d'
down_revision = '21be14a1e621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_to_user_id'), ['to_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_messages_from_user_id'))

    op.drop_table('messages')
    # ### end Alembic commands ###
