"""user-contact

Revision ID: 4fc387375f04
Revises: 10821bbc6b7d
Create Date: 2024-02-23 13:37:08.837813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc387375f04'
down_revision = '10821bbc6b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('inquiry', sa.Text(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_contacts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_contacts_user_id'))

    op.drop_table('user_contacts')
    # ### end Alembic commands ###
